server.port: 8761

eureka:
  instance:
    hostname: localhost
    metadataMap.zone: zone1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka/
    availabilityZones:
      region-1: zone1,zone2,defaultZone