server.port: 8762

eureka:
  instance:
    hostname: 127.0.0.1
    metadataMap.zone: zone2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    availabilityZones:
      region-1: zone2,zone1,defaultZone